### ISSUE TITLE
Missing metrics veeam_em_jobs_*

### ISSUE THREAD

**Issue by efficks** [peekjef72/veeam_exporter#3]
I've some missing metrics in VEEAM like veeam_em_jobs_sessions_retries. Do you have any idea why? Permission problem or VEEAM version?

Thank you

**Comment by efficks** [comment]
You can delete the issue. It's a license issue

**Comment by peekjef72** [comment]
Ok.
Maybe if you can or want to, can you update the doc (README) with rights/licence requirements ?
I'm an Admin of the monitoring tools not Veeam; so I've asked for a login that can access to date to the Veeam Admin, but really don't know that king of rights it  needs.
And as you have encoutered feature/licence trouble, maybe can you report what is missing with licence type X...
Thanks in advance.
