### ISSUE TITLE
diplay metrics export by veeam_exporter on grafana

### ISSUE THREAD

**Issue by tristanwrona** [peekjef72/veeam_exporter#4]
Hello, I have all the feedback from the veeam_exporter on my web page: http://hostname.domain:9248/metrics?target=host.domain , but how can I transmit them to prometheus to display them on grafana?

**Comment by peekjef72** [comment]
Hi,

Have a look at README.md: [Prometheus Config](https://github.com/peekjef72/veeam_exporter#prometheus-config):
- add a job in your promethues.yml configuration file. => your prometheus will start to collect the metrics.
- import the dashboards example (from dashboards directory) into your Grafana.

Tell me if it is OK for you.

**Comment by tristanwrona** [comment]
Hello, 

I finally made it! Sorry for the inconvenience. It's OK

**Comment by tristanwrona** [comment]
But after running the template, I notice a No Data in the Backup VMJob Status
